name: Deploy next branch to Vercel

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Preview

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            ref: next

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}